version: '3.8'
services:
    db:
      image: postgres
      container_name: db
      restart: always
      environment:
        - POSTGRES_PASSWORD=password123
        - POSTGRESQL_DATABASE=food
        - POSTGRES_USER=root
      ports:
          - "5432:5432"